### ISSUE TITLE
I have a need for speed!

### ISSUE THREAD

**Issue by pauloday** [ertdfgcb/quasicrystals#1]
This thing is real slow. It does a bunch of different sin/cos/asin operations for each pixel of each frame. Speed it up!
Possible optimziations:

- memoize sin/cos/asin
This is probably just a worse version of using a lookup table
- use a lookup table for sin/cos/asin
I only need accuracy to the thousandths on sin/cos. Specifically, I need 255 values from 0 to 1, distributed with sin/cos/asin.
- Utilize concurrency
Each pixel and frame is independent, so it should be pretty easy to parallelize. But the code will need to be restructured a bit to use pmap or agents.

Overall I'm going to try memozing since it's trivial, then a lookup table and compare. The concurrency can wait.

**Comment by pauloday** [comment]
Memoizing benchmark (64x36, 3 frames, order 6, scale 3)
before - 1116 ms
after - 1074 ms

Minor improvement. Let's see how the lookup table does.

**Comment by pauloday** [comment]
Turns out there's a [FastMath](https://github.com/generateme/fastmath) library for java that uses tables. I'm going to try that first. If the improvement isn't significant, I'll try [Riven's LUT based implementation](https://jvm-gaming.org/t/fast-math-sin-cos-lookup-tables/36660)

**Comment by pauloday** [comment]
After trying a bunch of memoization and sin/cos/asin implementations, I got no speed improvements for 640x360/20/6/1. Pretty lame, but that's the way she goes sometimes.

Next up is concurrency.

**Comment by ertdfgcb** [comment]
After some more looking into it, I've decided to rewrite in Rust (#4). Clojure probably has plenty of room to make it faster, but I think that effort would be better spent on Rust.

**Comment by pauloday** [comment]
After some more looking into it, I've decided to rewrite in Rust (#4). Clojure probably has plenty of room to make it faster, but I think that effort would be better spent on Rust.
